name: DigitalOcean Container Registry Tag Cleanup
description: Cleanup old Docker tags from DigitalOcean container registry
author: Timeraa
branding:
  icon: file-text
  color: blue
inputs:
  registry-name:
    description: Name of the DigitalOcean container registry
    required: true
  keep-versions:
    description: Number of recent versions to keep
    required: true
    default: '5'
  keep-semver:
    description: Number of unique semver versions to keep
    required: false
    default: '0'
  retention-days:
    description: Number of days to retain tags regardless of keep-versions
    required: false
    default: '0'
  dry-run:
    description: Perform a dry run without actually deleting tags
    required: false
    default: 'false'
  include-repos:
    description: Glob patterns to include specific repositories (one per line)
    required: false
  exclude-repos:
    description: Glob patterns to exclude specific repositories (one per line)
    required: false
  repo-concurrency:
    description: Number of repositories to process concurrently
    required: false
    default: '3'
  tag-concurrency:
    description: Number of tags to delete concurrently per repository
    required: false
    default: '3'
runs:
  using: node20
  main: dist/index.mjs
